### ISSUE TITLE
fix sms bug after sim replacement

### ISSUE THREAD

**Issue by NickCoolii** [aprilsacil/goip-php-api#3]
After sim replacement at goip-1 and goip-4 function getMessages() don't work until "delete all messages".
Screens are attached.
![http___192 168 10 40_8230_default_en_us_tools html_type sms_inbox code utf8 line -1 - waterfox 2018-11-04 17 56 40](https://user-images.githubusercontent.com/16125559/47965750-b8179880-e05b-11e8-88e9-48148d86d515.png)
![_new 5 - notepad 2018-11-04 17 57 43](https://user-images.githubusercontent.com/16125559/47965752-bbab1f80-e05b-11e8-8dc9-a34ee4de854f.png)

You can check my last commit for fix.
https://github.com/NickCoolii/goip-php-api/commit/cccb2b35353f2d8e6c648dca78183270238fc3a6

**Comment by aprilsacil** [comment]
https://github.com/aprilsacil/goip-php-api/commit/ef527a3c305bbdaa4d47b67b9e18aa2c7069c271
